services:
  - type: web
    name: starstruck-gallery
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    repo: https://github.com/hotweller123/starstruck-gallery.git
    branch: main
