/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as WalletSendRouteImport } from './routes/wallet.send'
import { Route as WalletSecurityRouteImport } from './routes/wallet.security'
import { Route as WalletDepositRouteImport } from './routes/wallet.deposit'
import { Route as WalletActivityRouteImport } from './routes/wallet.activity'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuctionsSlugRouteImport } from './routes/auctions.$slug'
import { Route as ArtworksSlugRouteImport } from './routes/artworks.$slug'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminExhibitionRouteImport } from './routes/admin.exhibition'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSendRoute = WalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSecurityRoute = WalletSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => WalletRoute,
} as any)
const WalletDepositRoute = WalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => WalletRoute,
} as any)
const WalletActivityRoute = WalletActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => WalletRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsSlugRoute = AuctionsSlugRouteImport.update({
  id: '/auctions/$slug',
  path: '/auctions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksSlugRoute = ArtworksSlugRouteImport.update({
  id: '/artworks/$slug',
  path: '/artworks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExhibitionRoute = AdminExhibitionRouteImport.update({
  id: '/exhibition',
  path: '/exhibition',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bids': typeof BidsRoute
  '/cart': typeof CartRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favourites': typeof FavouritesRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bids': typeof BidsRoute
  '/cart': typeof CartRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favourites': typeof FavouritesRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/admin': typeof AdminIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bids': typeof BidsRoute
  '/cart': typeof CartRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favourites': typeof FavouritesRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/exhibition': typeof AdminExhibitionRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/wallet/activity': typeof WalletActivityRoute
  '/wallet/deposit': typeof WalletDepositRoute
  '/wallet/security': typeof WalletSecurityRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bids'
    | '/cart'
    | '/connect'
    | '/contact'
    | '/favourites'
    | '/gallery'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/admin/exhibition'
    | '/admin/wallet'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/auctions/$slug'
    | '/categories/$slug'
    | '/wallet/activity'
    | '/wallet/deposit'
    | '/wallet/security'
    | '/wallet/send'
    | '/wallet/withdraw'
    | '/admin/'
    | '/artists/'
    | '/auctions/'
    | '/categories/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bids'
    | '/cart'
    | '/connect'
    | '/contact'
    | '/favourites'
    | '/gallery'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/admin/exhibition'
    | '/admin/wallet'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/auctions/$slug'
    | '/categories/$slug'
    | '/wallet/activity'
    | '/wallet/deposit'
    | '/wallet/security'
    | '/wallet/send'
    | '/wallet/withdraw'
    | '/admin'
    | '/artists'
    | '/auctions'
    | '/categories'
    | '/admin/users/$id'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bids'
    | '/cart'
    | '/connect'
    | '/contact'
    | '/favourites'
    | '/gallery'
    | '/profile'
    | '/sell'
    | '/wallet'
    | '/admin/exhibition'
    | '/admin/wallet'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/auctions/$slug'
    | '/categories/$slug'
    | '/wallet/activity'
    | '/wallet/deposit'
    | '/wallet/security'
    | '/wallet/send'
    | '/wallet/withdraw'
    | '/admin/'
    | '/artists/'
    | '/auctions/'
    | '/categories/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BidsRoute: typeof BidsRoute
  CartRoute: typeof CartRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  FavouritesRoute: typeof FavouritesRoute
  GalleryRoute: typeof GalleryRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRoute
  WalletRoute: typeof WalletRouteWithChildren
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ArtworksSlugRoute: typeof ArtworksSlugRoute
  AuctionsSlugRoute: typeof AuctionsSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/send': {
      id: '/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof WalletSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/security': {
      id: '/wallet/security'
      path: '/security'
      fullPath: '/wallet/security'
      preLoaderRoute: typeof WalletSecurityRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/deposit': {
      id: '/wallet/deposit'
      path: '/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof WalletDepositRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/activity': {
      id: '/wallet/activity'
      path: '/activity'
      fullPath: '/wallet/activity'
      preLoaderRoute: typeof WalletActivityRouteImport
      parentRoute: typeof WalletRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$slug': {
      id: '/auctions/$slug'
      path: '/auctions/$slug'
      fullPath: '/auctions/$slug'
      preLoaderRoute: typeof AuctionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$slug': {
      id: '/artworks/$slug'
      path: '/artworks/$slug'
      fullPath: '/artworks/$slug'
      preLoaderRoute: typeof ArtworksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exhibition': {
      id: '/admin/exhibition'
      path: '/exhibition'
      fullPath: '/admin/exhibition'
      preLoaderRoute: typeof AdminExhibitionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminExhibitionRoute: typeof AdminExhibitionRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExhibitionRoute: AdminExhibitionRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WalletRouteChildren {
  WalletActivityRoute: typeof WalletActivityRoute
  WalletDepositRoute: typeof WalletDepositRoute
  WalletSecurityRoute: typeof WalletSecurityRoute
  WalletSendRoute: typeof WalletSendRoute
  WalletWithdrawRoute: typeof WalletWithdrawRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletActivityRoute: WalletActivityRoute,
  WalletDepositRoute: WalletDepositRoute,
  WalletSecurityRoute: WalletSecurityRoute,
  WalletSendRoute: WalletSendRoute,
  WalletWithdrawRoute: WalletWithdrawRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BidsRoute: BidsRoute,
  CartRoute: CartRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  FavouritesRoute: FavouritesRoute,
  GalleryRoute: GalleryRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRoute,
  WalletRoute: WalletRouteWithChildren,
  ArtistsSlugRoute: ArtistsSlugRoute,
  ArtworksSlugRoute: ArtworksSlugRoute,
  AuctionsSlugRoute: AuctionsSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
